62 req 18 de gebruiker kan het weer
MirrorBoys/TheMirror pull request #141
Opened 2024-11-20 14:36 UTC by BvdG-HAN

Closes #62 

Let op: je moet de API key van KNMI invullen op [deze plek](https://github.com/MirrorBoys/TheMirror/blob/2882cc8ab900f0802b2f7ab1a18908d01c27c1fa/src/smartMirrorProject/theMirror/views.py#L47).

Let op: installeer Dutch locale op WSL/RPI:
```shell
sudo update-locale LANG=nl_NL.utf8
```

2024-11-20 15:54 UTC, Thorsten3 approved these changes
Netjes gedaan, mooi om te zien dat je functies schrijft die hergebruikt kunnen worden

2024-11-25 08:31 UTC, briandreuning requested changes
Klopt het dat ik nu de API key nog in de code zie staan?

2024-11-25 08:32 UTC, DarrenSamuels approved these changes

2024-11-25 12:56 UTC, DarrenSamuels submitted a review, later dismissed

2024-11-25 13:33 UTC, Thorsten3 requested changes
De slice is nu hardcoded, een aanpasbare variable zou beter zijn en er staan nog verschillende printlines in de code

2024-11-26 07:21 UTC, Thorsten3 submitted a review, later dismissed

2024-11-26 09:00 UTC, Thorsten3 submitted a review, later dismissed

2024-11-26 09:42 UTC, Thorsten3 submitted a review, later dismissed

2024-11-26 09:51 UTC, Thorsten3 submitted a review, later dismissed

2024-11-26 09:54 UTC, Thorsten3 approved these changes

2024-11-26 09:55 UTC, briandreuning approved these changes
Yes, werkt goed.

2024-11-26 09:55 UTC, merged