61 req 17 de gebruiker kan een reisplanner toevoegen aan de spiegel
MirrorBoys/TheMirror pull request #148
Opened 2024-11-21 10:07 UTC by briandreuning

Eerste concept is klaar. Hierbij wordt 1 trip laten zien in een tabel in een van de widget spots. Voor nu is het scrollen. API key uit de Teams halen want dat .env gebeuren wilde op een wonderbaarlijke manier niet werken.

2024-11-25 08:00 UTC, Thorsten3 approved these changes

2024-11-25 08:44 UTC, DarrenSamuels submitted a review, later dismissed

2024-11-25 14:11 UTC, Thorsten3 requested changes
CSS stijl in het daarvoor bedoelde css bestand

2024-11-25 14:18 UTC, briandreuning commented
> CSS stijl in het daarvoor bedoelde css bestand

Leuk, vertel je dat ook even aan news.html en time.html!!!!!!!!!!!!!!!!!

2024-11-26 09:24 UTC, Thorsten3 approved these changes

2024-11-26 09:25 UTC, merged