173 req 09 1 configureren django authenticatie 2
MirrorBoys/TheMirror pull request #188
Opened 2024-12-10 13:00 UTC by BvdG-HAN

Met deze PR wordt de loginpagina 'verbonden' met het Django authenticatiesysteem. Hierdoor kan je via [localhost:8000/login/](http://localhost:8000/login/) inloggen. Uitloggen gaat via [localhost:8000/logout/](http://localhost:8000/logout/) of de knop in de header. Alleen ingelogde gebruikers kunnen `homePage` bezoeken, niet-ingelogde gebruikers worden doorgestuurd naar `loginPage`.

Voor testdoeleinden heb ik een testgebruiker aangemaakt met gebruikersnaam `testuser` en wachtwoord `password123`. Deze moet je aanmaken met het `create_test_user.py`-script door middel van dit commando:

```shell
python manage.py runscript create_test_user
```

Ik heb voor de handigheid nog een ander script geschreven dat bovenstaande en onderstaande commando's uitvoert:

- `python3 -m pip install --upgrade pip`
- `pip install -r ~/TheMirror/src/smartMirrorProject/requirements.txt --no-cache-dir`
- `python3 manage.py migrate`
- `python3 manage.py runserver 0.0.0.0:8000`

Je kan dit script gebruiken als alternatief voor `python3 manage.py runserver` zodat je bovenstaande commando's niet vergeet:

```shell
python3 start_script.py
```

2024-12-11 14:04 UTC, Thorsten3 requested changes
Ik moet nu in de specifieke directories zitten om de scripts uit te kunnen voeren. Willen we niet consequent zijn en zorgen dat de scripts vanuit elke directory uit te voeren zijn

2024-12-11 14:10 UTC, briandreuning commented
Ik heb dezelfde feedback als Thorsten eigenlijk, de twee scripts die je hebt gemaakt staan nu in verschillende directories wat het wat minder gebruiksvriendelijk maakt.

2024-12-12 13:33 UTC, Thorsten3 requested changes
De logout knop lijkt niet te werken

2024-12-16 10:00 UTC, Thorsten3 approved these changes

2024-12-16 11:03 UTC, briandreuning approved these changes
Heb dit zojuist getest en het lijkt allemaal goed te werken. Ik kan inloggen en uitloggen. De default page is de login page zoals afgesproken. Als je bent ingelogd dan kan je de spiegel zien.

2024-12-16 11:03 UTC, merged